language: go
go: 
 - 1.7.6

script:
 - go get -u github.com/kardianos/govendor
 - govendor build +local
 - GOOS=linux GOARCH=amd64 go build -o logstash_exporter
 - tar -zcvf logstash_exporter_amd64.tar.gz logstash_exporter

deploy:
  provider: s3
  access_key_id: "$ARTIFACTS_SECRET"
  secret_access_key: "$$ARTIFACTS_KEY"
  bucket: "homelessnessbo"
  skip_cleanup: true
